In [2]:
import cv2
import numpy as np

In [24]:
img = cv2.imread('/content/green image.jfif')

In [25]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [26]:
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

In [27]:
h,s,v = cv2.split(hsv)


In [29]:
print(hsv)

[[[111 253 154]
  [111 253 154]
  [111 253 154]
  ...
  [109 253 160]
  [109 250 162]
  [109 247 164]]

 [[111 253 154]
  [111 253 154]
  [111 253 154]
  ...
  [109 252 161]
  [109 250 162]
  [109 250 162]]

 [[111 253 154]
  [111 253 154]
  [111 253 154]
  ...
  [109 250 164]
  [109 252 163]
  [109 252 163]]

 ...

 [[ 44 191  91]
  [ 44 191  91]
  [ 43 182  98]
  ...
  [ 46 212  77]
  [ 46 204  80]
  [ 46 197  83]]

 [[ 44 217  80]
  [ 44 193  90]
  [ 43 179 100]
  ...
  [ 46 197  83]
  [ 46 194  84]
  [ 46 192  85]]

 [[ 44 206  84]
  [ 44 199  87]
  [ 43 215  83]
  ...
  [ 46 194  84]
  [ 46 194  84]
  [ 46 197  83]]]


In [30]:
lower_h = 35
upper_h = 85

In [31]:
mask =cv2.inRange(h, lower_h, upper_h)

In [32]:
result = cv2.bitwise_and(img, img, mask=mask)

In [33]:
print(mask)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [35]:
cv2.imwrite('mask.jpg',result)

True

In [39]:
# Save original image
cv2.imwrite(r'"C:\Users\harshit\Desktop\lab8"original.jpg', img)

True

In [40]:
# Save HSV image (note: colors will look different if opened normally)
cv2.imwrite(r'"C:\Users\harshit\Desktop\lab8"hsv.jpg', hsv)

# Save individual channels
cv2.imwrite(r'"C:\Users\harshit\Desktop\lab8"hue.jpg', h)
cv2.imwrite(r'"C:\Users\harshit\Desktop\lab8"saturation.jpg', s)
cv2.imwrite(r'"C:\Users\harshit\Desktop\lab8"value.jpg', v)

# Save final filtered result
cv2.imwrite(r'"C:\Users\harshit\Desktop\lab8"filtered_green.jpg', result)

True